tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-secondary-fixed": "#1c1b1b",
                        "inverse-primary": "#c00014",
                        "on-surface-variant": "#e8bcb7",
                        "background": "#121414",
                        "on-primary-fixed": "#410002",
                        "on-tertiary-container": "#262a2d",
                        "outline-variant": "#5e3f3c",
                        "primary-container": "#ff544b",
                        "surface-dim": "#121414",
                        "secondary": "#c8c6c5",
                        "surface-container": "#1e2020",
                        "on-secondary-fixed-variant": "#474646",
                        "surface-container-low": "#1a1c1c",
                        "primary-fixed-dim": "#ffb4ab",
                        "inverse-on-surface": "#2f3131",
                        "surface-container-highest": "#333535",
                        "on-secondary-container": "#bab8b7",
                        "surface": "#121414",
                        "primary-fixed": "#ffdad6",
                        "tertiary-container": "#8d9194",
                        "on-error-container": "#ffdad6",
                        "surface-tint": "#ffb4ab",
                        "primary": "#ffb4ab",
                        "secondary-fixed-dim": "#c8c6c5",
                        "secondary-fixed": "#e5e2e1",
                        "surface-variant": "#333535",
                        "surface-container-lowest": "#0c0f0f",
                        "on-tertiary-fixed-variant": "#43474a",
                        "on-tertiary-fixed": "#181c1f",
                        "surface-bright": "#37393a",
                        "inverse-surface": "#e2e2e2",
                        "secondary-container": "#4a4949",
                        "error": "#ffb4ab",
                        "tertiary-fixed-dim": "#c3c7ca",
                        "outline": "#ae8783",
                        "on-error": "#690005",
                        "on-tertiary": "#2d3134",
                        "error-container": "#93000a",
                        "on-secondary": "#313030",
                        "on-surface": "#e2e2e2",
                        "tertiary": "#c3c7ca",
                        "on-primary-fixed-variant": "#93000d",
                        "tertiary-fixed": "#dfe3e6",
                        "on-primary-container": "#5c0005",
                        "on-primary": "#690006",
                        "surface-container-high": "#282a2b",
                        "on-background": "#e2e2e2",
                        "accent-gold": "#f0a500",
                        "accent-teal": "#00b4d8",
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "xl": "80px",
                        "gutter": "24px",
                        "lg": "48px",
                        "sm": "12px",
                        "xs": "4px",
                        "margin-mobile": "16px",
                        "margin-desktop": "40px",
                        "md": "24px",
                        "base": "8px"
                    },
                    "fontFamily": {
                        "body-lg": ["Open Sans"],
                        "label-mono": ["JetBrains Mono"],
                        "headline-lg": ["Raleway"],
                        "headline-md": ["Raleway"],
                        "headline-xl": ["Raleway"],
                        "data-display": ["JetBrains Mono"],
                        "body-md": ["Open Sans"],
                        "headline-lg-mobile": ["Raleway"]
                    },
                    "fontSize": {
                        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                        "label-mono": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
                        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                        "data-display": ["20px", {"lineHeight": "1.0", "fontWeight": "700"}],
                        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}]
                    }
                },
            },
        }
